"""AdvanCore local agent runner foundation.

This package provides a fail-closed orchestration control plane for bounded
AI-assisted development tasks. It discovers task files, validates repository
safety preconditions, generates canonical worker instructions, and abstracts
worker execution behind a replaceable adapter.

The default behaviour is dry-run / planning only. Actual worker execution is
opt-in and still leaves commit, push, merge, and other high-impact actions
gated for explicit human approval.
"""

from advancore.agent_runner.controller_decision import (
    ControllerDecision,
    ControllerDecisionError,
    ControllerDecisionWriteError,
    DecisionValue,
    build_controller_decision,
    default_decisions_dir,
    find_latest_decision,
    format_decision_summary,
    load_controller_decision,
    write_controller_decision,
)
from advancore.agent_runner.controller_handoff import (
    ControllerHandoff,
    ControllerHandoffError,
    ControllerHandoffWriteError,
    HandoffReconciliationResult,
    HandoffState,
    build_controller_handoff,
    default_handoff_dir,
    find_latest_handoff,
    format_handoff_summary,
    load_controller_handoff,
    reconcile_controller_handoff,
    write_controller_handoff,
)
from advancore.agent_runner.controller_transport_driver import (
    ControllerTransportDriver,
    ControllerTransportDriverAmbiguousError,
    ControllerTransportDriverConflictError,
    ControllerTransportDriverError,
    ControllerTransportDriverNotFoundError,
    DriverArtifactView,
    LocalFilesystemTransportDriver,
    default_driver_dirs,
    load_driver_request_by_id,
    write_driver_response,
)
from advancore.agent_runner.decision_lifecycle_bridge import (
    DecisionLifecycleBridgeError,
    DecisionLifecycleResult,
    apply_controller_decision,
)
from advancore.agent_runner.finalize import (
    FinalizationError,
    FinalizationResult,
    FinalizationStatus,
    default_finalize_dir,
    format_finalization_result,
    run_finalization,
)
from advancore.agent_runner.git_info import GitInfo, get_git_info
from advancore.agent_runner.goal_task import (
    GoalTaskError,
    GoalTaskGenerationResult,
    GoalTaskGenerationStatus,
    GoalTaskProposal,
    OwnerGoal,
    OwnerGoalError,
    ProposalError,
    RepositoryMutationError,
    TaskIdAssignmentError,
    assign_next_task_id,
    build_planner_instruction,
    build_task_filename,
    capture_repository_snapshot,
    default_goal_task_dir,
    detect_repository_mutation,
    format_goal_task_report,
    generate_goal_task,
    parse_planner_output,
    render_task_markdown,
    validate_owner_goal,
    validate_proposal,
    write_goal_task_artifact,
)
from advancore.agent_runner.review_bundle import (
    ControllerAction,
    ReviewBundle,
    ReviewBundleError,
    ReviewBundleWriteError,
    build_review_bundle,
    default_review_dir,
    find_latest_bundle,
    format_bundle_summary,
    load_review_bundle,
    write_review_bundle,
)
from advancore.agent_runner.lifecycle import (
    ActorRole,
    LifecycleResult,
    TaskStatus,
    is_transition_allowed,
    transition_task,
)
from advancore.agent_runner.auto_pipeline import (
    AutoPipelineResult,
    AutoPipelineStatus,
    DiffCheckResult,
    PytestResult,
    RepairAttempt,
    RepairConfig,
    RepairStatus,
    ScopeResult,
    build_scope_result,
    classify_repair_status,
    default_auto_dir,
    format_auto_pipeline_report,
    parse_task_allowed_scope,
    run_auto_pipeline,
    run_git_diff_check,
    run_pytest,
)
from advancore.agent_runner.runner import (
    PostWorkerVerification,
    RunnerResult,
    RunnerStatus,
    execute,
    plan,
)
from advancore.agent_runner.task import (
    Task,
    TaskError,
    discover_tasks,
    find_task,
    parse_task,
)
from advancore.agent_runner.validation import ValidationResult, validate
from advancore.agent_runner.worker import (
    DryRunWorkerAdapter,
    KimiSwarmWorkerAdapter,
    KimiWorkerAdapter,
    WorkerAdapter,
    WorkerResult,
    build_kimi_swarm_instruction,
    build_worker_instruction,
)

__all__ = [
    "ActorRole",
    "AutoPipelineResult",
    "AutoPipelineStatus",
    "ControllerAction",
    "ControllerDecision",
    "ControllerDecisionError",
    "ControllerDecisionWriteError",
    "ControllerHandoff",
    "ControllerHandoffError",
    "ControllerHandoffWriteError",
    "ControllerTransportDriver",
    "ControllerTransportDriverAmbiguousError",
    "ControllerTransportDriverConflictError",
    "ControllerTransportDriverError",
    "ControllerTransportDriverNotFoundError",
    "DecisionLifecycleBridgeError",
    "DecisionLifecycleResult",
    "DecisionValue",
    "DiffCheckResult",
    "FinalizationError",
    "FinalizationResult",
    "FinalizationStatus",
    "DriverArtifactView",
    "GitInfo",
    "GoalTaskError",
    "GoalTaskGenerationResult",
    "GoalTaskGenerationStatus",
    "GoalTaskProposal",
    "OwnerGoal",
    "OwnerGoalError",
    "ProposalError",
    "RepositoryMutationError",
    "TaskIdAssignmentError",
    "assign_next_task_id",
    "build_planner_instruction",
    "build_task_filename",
    "capture_repository_snapshot",
    "default_goal_task_dir",
    "detect_repository_mutation",
    "format_goal_task_report",
    "generate_goal_task",
    "parse_planner_output",
    "render_task_markdown",
    "validate_owner_goal",
    "validate_proposal",
    "write_goal_task_artifact",
    "HandoffReconciliationResult",
    "HandoffState",
    "KimiSwarmWorkerAdapter",
    "LifecycleResult",
    "LocalFilesystemTransportDriver",
    "PytestResult",
    "ReviewBundle",
    "ReviewBundleError",
    "ReviewBundleWriteError",
    "ScopeResult",
    "apply_controller_decision",
    "build_controller_decision",
    "build_controller_handoff",
    "build_kimi_swarm_instruction",
    "build_review_bundle",
    "build_scope_result",
    "default_auto_dir",
    "default_decisions_dir",
    "default_driver_dirs",
    "default_finalize_dir",
    "default_handoff_dir",
    "default_review_dir",
    "find_latest_decision",
    "find_latest_handoff",
    "find_latest_bundle",
    "format_auto_pipeline_report",
    "format_decision_summary",
    "format_bundle_summary",
    "format_finalization_result",
    "format_handoff_summary",
    "load_controller_decision",
    "load_controller_handoff",
    "load_driver_request_by_id",
    "load_review_bundle",
    "parse_task_allowed_scope",
    "reconcile_controller_handoff",
    "run_auto_pipeline",
    "run_finalization",
    "run_git_diff_check",
    "run_pytest",
    "write_controller_decision",
    "write_controller_handoff",
    "write_driver_response",
    "write_review_bundle",
    "PostWorkerVerification",
    "RunnerResult",
    "RunnerStatus",
    "Task",
    "TaskError",
    "TaskStatus",
    "ValidationResult",
    "WorkerAdapter",
    "WorkerResult",
    "build_worker_instruction",
    "discover_tasks",
    "execute",
    "find_task",
    "get_git_info",
    "is_transition_allowed",
    "parse_task",
    "plan",
    "transition_task",
    "validate",
    "DryRunWorkerAdapter",
    "KimiWorkerAdapter",
]
